name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dependencies:
    runs-on: ubuntu-latest
    env:
      CI: true
    strategy:
      matrix:
        node: ["12", "14", "16"]
    name: Node ${{ matrix.node }} Dependencies
    steps:
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "America/Mexico_City"
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install NPM Packages (Base)
        run: yarn install
        working-directory: packages/base
      - name: Install NPM Packages (Case)
        run: yarn install
        working-directory: packages/case
      - name: Install NPM Packages (Date)
        run: yarn install
        working-directory: packages/date

  report:
    needs: ["test-base", "test-case", "test-date"]
    runs-on: ubuntu-latest
    env:
      CI: true
    strategy:
      matrix:
        node: ["16"]
    name: Node ${{ matrix.node }} Reports
    steps:
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "America/Mexico_City"
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - name: Display structure of downloaded files
        run: ls -R
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: codecov-umbrella
          verbose: true
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - uses: c-hive/gha-yarn-cache@v2
      - name: Codecov Node
        env:
          CODECOV_URL: ${{ secrets.LIBRECOV_ENDPOINT }}
          CODECOV_TOKEN: ${{ secrets.LIBRECOV_TOKEN }}
        run: |
          yarn add codecov
          npx codecov --disable=s3
      - name: Coveralls
        uses: coverallsapp/github-action@master
        continue-on-error: true
        with:
          github-token: ${{ secrets.LIBRECOV_TOKEN }}
          coveralls-endpoint: ${{ secrets.LIBRECOV_ENDPOINT }}
          parallel-finished: true


  test-base:
    needs: ["dependencies"]
    runs-on: ubuntu-latest
    env:
      CI: true
    strategy:
      matrix:
        node: ["12", "14", "16"]
    name: Node ${{ matrix.node }} base tests
    steps:
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "America/Mexico_City"
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install NPM Packages
        run: yarn install
        working-directory: packages/base
      - name: Test
        run: yarn test --coverage
        working-directory: packages/base
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: base-cov
          path: packages/base/coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          git-branch: ${{env.GITHUB_HEAD_REF}}
          github-token: ${{ secrets.LIBRECOV_TOKEN }}
          coveralls-endpoint: ${{ secrets.LIBRECOV_ENDPOINT }}
          flag-name: base-cov
          parallel: true
          path-to-lcov: packages/base/coverage/lcov.info
          base-path: "${{env.GITHUB_WORKSPACE}}/packages/base"

  test-case:
    needs: ["dependencies"]
    runs-on: ubuntu-latest
    env:
      CI: true
    strategy:
      matrix:
        node: ["12", "14", "16"]
    name: Node ${{ matrix.node }} case tests
    steps:
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "America/Mexico_City"
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install NPM Packages
        run: yarn install
        working-directory: packages/case
      - name: Test
        run: yarn test --coverage
        working-directory: packages/case
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: case-cov
          path: packages/case/coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          git-branch: ${{env.GITHUB_HEAD_REF}}
          github-token: ${{ secrets.LIBRECOV_TOKEN }}
          coveralls-endpoint: ${{ secrets.LIBRECOV_ENDPOINT }}
          flag-name: case-cov
          parallel: true
          path-to-lcov: packages/case/coverage/lcov.info
          base-path: "${{env.GITHUB_WORKSPACE}}/packages/case"

  test-date:
    needs: ["dependencies"]
    runs-on: ubuntu-latest
    env:
      CI: true
    strategy:
      matrix:
        node: ["12", "14", "16"]
    name: Node ${{ matrix.node }} date tests
    steps:
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "America/Mexico_City"
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install NPM Packages
        run: yarn install
        working-directory: packages/date
      - name: Test
        run: yarn test --coverage
        working-directory: packages/date
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: date-cov
          path: packages/date/coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          git-branch: ${{env.GITHUB_HEAD_REF}}
          github-token: ${{ secrets.LIBRECOV_TOKEN }}
          coveralls-endpoint: ${{ secrets.LIBRECOV_ENDPOINT }}
          flag-name: date-cov
          parallel: true
          path-to-lcov: packages/date/coverage/lcov.info
          base-path: "${{env.GITHUB_WORKSPACE}}/packages/date"
